[package]
name = "portenta-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
vcell = "0.1.3"
portable-atomic = "1.11.0"


[features]
critical-section = []
rt = ["cortex-m-rt/device"]
